eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8082
spring:
  application:
    name: common-cloud-provider
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: user-db